name = "wywiwya-rss"
workers_dev = true
compatibility_date = "2022-04-14"
main = "build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
# --no-default-features: BUG https://github.com/rustwasm/wasm-pack/issues/1186
command = "cargo install -q wasm-pack --no-default-features && cargo install -q worker-build && worker-build --release"
