name = "wywiwya-rss"
account_id = "9d48568bcdcd05a662c026f28745dd1c"
workers_dev = true
compatibility_date = "2022-04-14"
main = "build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build && worker-build --release"
